#!/usr/bin/env bash
#create a symbolic link b/n nginx configuration and nginx enabled files
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"