#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific messages for the 4th, 9th, and 17th iterations

counter=1

while [ $counter -le 20 ]; do
  echo -n "$counter "

  case $counter in
    4)
      echo ""
      echo "and then bad luck from China"
      ;;
    9)
      echo ""
      echo "and then bad luck from Japan"
      ;;
    17)
      echo ""
      echo "and then bad luck from Italy"
      ;;
    *)
      echo "" # Just a new line for other numbers
      ;;
  esac

  ((counter++))
done
