#!/usr/bin/env bash
#A Bash script that accepts one argument
#The script should run the whoami command under the user passed as an argument
#Make sure to try your script by passing different users
su -u "$1" whoami